#!/usr/bin/env python3
"""Rebuild the chatbot's knowledge file from the site's pages.

Run from the repo root after editing any page:
    python3 tools/build-chat-knowledge.py

It copies the visible text inside <main> of each page into
netlify/functions/chat/knowledge.mjs, so the assistant only knows what the
site actually says.
"""
from html.parser import HTMLParser
from pathlib import Path
import json

PAGES = [
    ("index.html", "Home"),
    ("india.html", "Studying in India"),
    ("abroad.html", "Studying abroad"),
    ("schools.html", "For schools"),
    ("about.html", "About Campuscout"),
    ("guides.html", "Free guides"),
    ("guide-us-assistantships.html", "Guide: US graduate assistantships"),
    ("guide-germany.html", "Guide: tuition-free study in Germany"),
    ("careers.html", "Careers at Campuscout"),
]
SKIP = {"script", "style", "form", "svg", "button", "select", "noscript"}
BLOCK = {"p", "li", "h1", "h2", "h3", "summary", "div", "section", "figcaption", "details"}


class MainText(HTMLParser):
    def __init__(self):
        super().__init__()
        self.in_main = 0
        self.skip = 0
        self.out = []

    def handle_starttag(self, tag, attrs):
        if tag == "main":
            self.in_main += 1
        elif tag in SKIP:
            self.skip += 1
        if self.in_main and not self.skip:
            if tag in ("h1", "h2"):
                self.out.append("\n\n## ")
            elif tag in ("h3", "summary"):
                self.out.append("\n\n### ")
            elif tag == "li":
                self.out.append("\n- ")
            elif tag in BLOCK:
                self.out.append("\n")
            else:
                self.out.append(" ")

    def handle_endtag(self, tag):
        if tag == "main":
            self.in_main -= 1
        elif tag in SKIP:
            self.skip -= 1

    def handle_data(self, data):
        if self.in_main and not self.skip:
            self.out.append(" ".join(data.split()) if data.strip() else " ")

    def text(self):
        lines = [" ".join(l.split()) for l in "".join(self.out).splitlines()]
        cleaned, blank = [], False
        for l in lines:
            if not l:
                if not blank:
                    cleaned.append("")
                blank = True
            else:
                cleaned.append(l)
                blank = False
        return "\n".join(cleaned).strip()


root = Path(__file__).resolve().parent.parent
parts = []
for fname, title in PAGES:
    p = MainText()
    p.feed((root / fname).read_text(encoding="utf-8"))
    parts.append(f'<page title="{title}" url="/{fname}">\n{p.text()}\n</page>')

knowledge = "\n\n".join(parts)
out = root / "netlify/functions/chat/knowledge.mjs"
out.write_text(
    "// Generated by tools/build-chat-knowledge.py from the site's pages. Do not edit by hand.\n"
    f"export default {json.dumps(knowledge, ensure_ascii=False)};\n",
    encoding="utf-8",
)
print(f"wrote {out.relative_to(root)} ({len(knowledge):,} characters from {len(PAGES)} pages)")
